network.host: _ec2:privateIpv4_
network.bind_host: 0.0.0.0
network.publish_host: 0.0.0.0
discovery:
    zen.hosts_provider: ec2
cloud.node.auto_attributes: true
cluster.routing.allocation.awareness.attributes: aws_availability_zone
