version: '2'

services:
  elasticsearch:
    build: ./elasticsearch/
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - bootstrap.memory_lock=true
      - cluster.name=elktest
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    networks:
      - docker_elk
    labels:
      io.rancher.scheduler.affinity:host_label: region=us-east-1
  logstash:
    build: ./logstash
    command: -f /etc/logstash/conf.d/
    ports:
      - "5000:5000"
      - "5010:5010"
      - "5044:5044"
      - "1514:1514"
    networks:
      - docker_elk
    depends_on:
      - elasticsearch
    labels:
      io.rancher.scheduler.affinity:host_label: region=us-east-1
  kibana:
    build: ./kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - docker_elk
    depends_on:
      - elasticsearch
    labels:
       io.rancher.scheduler.affinity:host_label: region=us-east-1

networks:
  docker_elk:
    driver: overlay
